package aws.gamelift.server;

/// <summary>
/// This data type is used to identify which files generated during a
/// game session that you want GameLift to upload and store once the
/// game session ends. This information is communicated to GameLift in a
/// ProcessReady() call.
/// </summary>
class LogParameters {
	/// <summary>
	/// List of directory paths to game server log files you want GameLift
	/// to store for future access. These files are generated by a server
	/// process during each game session; file paths and names are defined
	/// in your game server and stored in the root game build directory.
	/// The log paths must be absolute.<br/>
	/// For example, if your game build stores game session logs in a path
	/// like <c>MyGame\sessionlogs\</c>, then the log path would be
	/// <c>c:\game\MyGame\sessionLogs</c> (on a Windows instance) or
	/// <c>/local/game/MyGame/sessionLogs</c> (on a Linux instance).
	/// </summary>
	public var LogPaths:Array<String>;

	public function new(logPaths : Array<String> = null)
	{
		LogPaths = logPaths != null ? logPaths : [];
	}
}
